# Generated by Django 2.2.1 on 2019-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_reporter',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
